spring:
  profiles:
    active: db, server, firebase
  jackson:
    serialization:
      indent-output: true
logging:
  level:
    root: info
    org:
      springframework:
        jdbc:
          core:
            org.springframework.jdbc.core.JdbcTemplate: error
      hibernate:
        sql: error
