
spring:
  profiles:
    active: db, server
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    serialization:
      indent-output: true
  sql:
    init:
      mode: always

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

springdoc:
  default-consumes-media-type: application/json
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
  use-fqn: true

