 name: Java CI with Gradle

 on:
   push:
     branches: [ "main" ]

 permissions:
   contents: read

 jobs:
   build:

     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v3
     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'temurin'

     - name: chmod
       run: sudo chmod 400 ./gradlew

     - name: Build with Gradle
       run: ./gradlew bootJar

     - name: web docker build and push
       run: |
         docker login -u ${{ secrets.DOCKER_EMAIL }} -p ${{ secrets.DOCKER_PASSWORD }}
         docker build -t ${{ secrets.DOCKER_ID }}/weteam .
         docker push ${{ secrets.DOCKER_ID }}/weteam

     ## docker compose up
     - name: executing remote ssh commands using password
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.HOST }}
         username: ubuntu
         key: ${{ secrets.KEY }}
         script: |
           sudo docker rm -f $(docker ps -qa)
           sudo docker pull ${{ secrets.DOCKER_ID }}/weteam
           docker run -d -p 9090:8080 ${{ secrets.DOCKER_ID }}/weteam
           docker image prune -f
